---
#############################################
### config for gitlabci-local
#############################################
.local                 :
    after: true
    all: false
    before: true
    display: true
    dump: true
    engine: docker,auto
    list: true
    manual: true
    network: host
    notify: true
    pipeline: false
    pull: true
    real_paths: true
    rmi: true
    sockets: true


image                  : node:lts-alpine

stages                 :
-   test
-   build
-   deploy

cache                  :
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    -   node_modules/

before_script          :
-   npm install

test                   :
    stage: test
    script:
    -   npm run test

build                  :
    stage: build
    script:
    -   npm run build
    artifacts:
        paths:
        -   dist

publish_gitlab_registry:
    stage: deploy
    needs:
    -   job: build
        artifacts: true
    dependencies:
    -   build
    script:
    -   npm config set ${ORANIZATION}:registry https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
    -   npm config set -- '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    -   npm config set -- '//gitlab.com/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    -   npm publish
    rules:
    -   if: $CI_COMMIT_TAG

publish_npm            :
    stage: deploy
    needs:
    -   job: build
        artifacts: true
    dependencies:
    -   build
    script:
    -   npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
    -   npm publish --access public
    rules:
    -   if: $CI_COMMIT_TAG
