sonar.projectKey=chrysa_container-webview
sonar.organization=chrysa
sonar.projectName=container-webview

sonar.sources=api/app,code/src
sonar.tests=api/app/tests
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/node_modules/**,**/.git/**,**/dist/**,**/.vscode/**,**/*.egg-info/**
sonar.test.inclusions=api/app/tests/**

sonar.python.version=3.12,3.13,3.14
sonar.python.coverage.reportPaths=api/coverage.xml
sonar.javascript.lcov.reportPaths=code/coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**
